-- create admin user
create role root with superuser = true and login = true and password = 'admin';

-- create keyspace with 3 replicas
create keyspace flight_delay with replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

-- create mysql table
CREATE TABLE mysql (
  year bigint,
  quarter bigint,
  month bigint,
  dayofmonth bigint,
  dayofweek bigint,
  flightdate text,
  reporting_airline text,
  dot_id_reporting_airline bigint,
  iata_code_reporting_airline text,
  tail_number text,
  flight_number_reporting_airline bigint,
  originairportid bigint,
  originairportseqid bigint,
  origincitymarketid bigint,
  origin text,
  origincityname text,
  originstate text,
  originstatefips bigint,
  originstatename text,
  originwac bigint,
  destairportid bigint,
  destairportseqid bigint,
  destcitymarketid bigint,
  dest text,
  destcityname text,
  deststate text,
  deststatefips bigint,
  deststatename text,
  destwac bigint,
  crsdeptime bigint,
  deptime double,
  depdelay double,
  depdelayminutes double,
  depdel15 double,
  departuredelaygroups double,
  deptimeblk text,
  taxiout double,
  wheelsoff double,
  wheelson double,
  taxiin double,
  crsarrtime bigint,
  arrtime double,
  arrdelay double,
  arrdelayminutes double,
  arrdel15 double,
  arrivaldelaygroups double,
  arrtimeblk text,
  cancelled double,
  cancellationcode text,
  diverted double,
  crselapsedtime double,
  actualelapsedtime double,
  airtime double,
  flights double,
  distance double,
  distancegroup bigint,
  carrierdelay double,
  weatherdelay double,
  nasdelay double,
  securitydelay double,
  lateaircraftdelay double,
  id bigint,
  PRIMARY KEY (id)
);

-- create mongodb table
CREATE TABLE mongodb (
  year bigint,
  quarter bigint,
  month bigint,
  dayofmonth bigint,
  dayofweek bigint,
  flightdate text,
  reporting_airline text,
  dot_id_reporting_airline bigint,
  iata_code_reporting_airline text,
  tail_number text,
  flight_number_reporting_airline bigint,
  originairportid bigint,
  originairportseqid bigint,
  origincitymarketid bigint,
  origin text,
  origincityname text,
  originstate text,
  originstatefips bigint,
  originstatename text,
  originwac bigint,
  destairportid bigint,
  destairportseqid bigint,
  destcitymarketid bigint,
  dest text,
  destcityname text,
  deststate text,
  deststatefips bigint,
  deststatename text,
  destwac bigint,
  crsdeptime bigint,
  deptime double,
  depdelay double,
  depdelayminutes double,
  depdel15 double,
  departuredelaygroups double,
  deptimeblk text,
  taxiout double,
  wheelsoff double,
  wheelson double,
  taxiin double,
  crsarrtime bigint,
  arrtime double,
  arrdelay double,
  arrdelayminutes double,
  arrdel15 double,
  arrivaldelaygroups double,
  arrtimeblk text,
  cancelled double,
  cancellationcode text,
  diverted double,
  crselapsedtime double,
  actualelapsedtime double,
  airtime double,
  flights double,
  distance double,
  distancegroup bigint,
  carrierdelay double,
  weatherdelay double,
  nasdelay double,
  securitydelay double,
  lateaircraftdelay double,
  id bigint,
  PRIMARY KEY (id)
);
