version: '3'

networks:
  mongodb:
    external: true

services:
  mongo-1:
    image: mongo:latest
    hostname: mongo-1
    container_name: mongo-1
    ports:
      - 27017:27017
    networks:
      - mongodb
    volumes:
      - /Users/trantrieuvu/Desktop/mongodb1:/data/db
    restart: always
    command: mongod --replSet rs0

  mongo-2:
    image: mongo:latest
    hostname: mongo-2
    container_name: mongo-2
    ports:
      - 27018:27017
    networks:
      - mongodb
    volumes:
      - /Users/trantrieuvu/Desktop/mongodb2:/data/db
    restart: always
    command: mongod --replSet rs0

  mongo-3:
    image: mongo:latest
    hostname: mongo-3
    container_name: mongo-3
    ports:
      - 27019:27017
    networks:
      - mongodb
    volumes:
      - /Users/trantrieuvu/Desktop/mongodb3:/data/db
    restart: always
    command: mongod --replSet rs0