version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    restart: always
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: root
      MB_DB_PASS: admin
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metabase
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ~/Desktop/metabase/pgdata/:/var/lib/postgresql/data
